// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-hotel-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var HOTEL_INFO = {
  name: "The Woodpecker Inn",
  location: "VPO Jibhi, Gadagushaini, Himachal Pradesh 175123, India",
  phone: "+91 93172 24562",
  whatsapp: "+91 93172 24562",
  email: "support@thewoodpeckerinn.in",
  website: "https://www.thewoodpeckerinn.in",
  instagram: "https://www.instagram.com/thewoodpeckerinnjibhi/",
  rooms: [
    "Deluxe Double with Balcony",
    "King Room with Balcony",
    "Queen Room with Balcony",
    "Double Room with Balcony",
    "Standard Double",
    "Classic Quadruple",
    "Mixed Dorm",
    "Female Dorm"
  ],
  amenities: [
    "In-house cafe",
    "Pet-friendly",
    "Free Wi-Fi",
    "Valley views",
    "24/7 support"
  ],
  positioning: "Boutique mountain retreat in Jibhi Valley, Himachal Pradesh \u2014 designed for digital nomads and luxury travelers."
};
var get_hotel_info_default = defineTool({
  name: "get_hotel_info",
  title: "Get hotel info",
  description: "Returns The Woodpecker Inn's location, contact details, room types, and amenities.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(HOTEL_INFO, null, 2) }],
    structuredContent: HOTEL_INFO
  })
});

// src/lib/mcp/tools/create-booking-inquiry.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_booking_inquiry_default = defineTool2({
  name: "create_booking_inquiry",
  title: "Create a booking inquiry",
  description: "Submit a new booking inquiry for The Woodpecker Inn on behalf of the signed-in user. Staff will follow up via email/WhatsApp.",
  inputSchema: {
    name: z.string().trim().min(1).describe("Guest full name"),
    phone: z.string().trim().min(6).describe("Contact phone with country code"),
    checkIn: z.string().describe("Check-in date, YYYY-MM-DD"),
    checkOut: z.string().describe("Check-out date, YYYY-MM-DD"),
    guests: z.number().int().min(1).max(20).describe("Number of guests"),
    message: z.string().trim().optional().describe("Special requests, optional")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, phone, checkIn, checkOut, guests, message }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return {
        content: [{ type: "text", text: "No email on the signed-in user" }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("booking_inquiries").insert({
      name,
      email,
      phone,
      check_in: checkIn,
      check_out: checkOut,
      guests,
      message: message ?? null
    }).select().single();
    if (error) {
      return {
        content: [{ type: "text", text: `Failed to create inquiry: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Inquiry received. Reference: ${data.id}. The team will contact ${email} within 24 hours.`
        }
      ],
      structuredContent: { inquiry: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ifnvatfypahnazxckwxf";
var mcp_default = defineMcp({
  name: "woodpecker-inn-mcp",
  title: "The Woodpecker Inn",
  version: "0.1.0",
  instructions: "Tools for The Woodpecker Inn (Jibhi, Himachal Pradesh). Use `get_hotel_info` for property details and `create_booking_inquiry` to submit a booking request on behalf of the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_hotel_info_default, create_booking_inquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
